<?php
/**
 * @author: Ylambers <yaron.lambers@commercetools.de>
 */

namespace Commercetools\Symfony\CtpBundle\DependencyInjection;


use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('commercetools');

        $rootNode
            ->children()
                ->arrayNode('api')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_client')->defaultValue('default')->end()
                        ->arrayNode('clients')
                            ->fixXmlConfig('client')
                            ->useAttributeAsKey('name')
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('client_id')->isRequired()->end()
                                    ->scalarNode('client_secret')->isRequired()->end()
                                    ->scalarNode('project')->isRequired()->end()
                                    ->scalarNode('scope')->end()
                                    ->scalarNode('api_url')->end()
                                    ->scalarNode('oauth_url')->end()
                                    ->booleanNode('throwExceptions')->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('defaults')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('country')->defaultValue('US')->end()
                        ->arrayNode('context')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('locale')->defaultValue('en')->end()
                                ->booleanNode('graceful')->defaultValue(true)->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('cache')
                    ->prototype('boolean')->end()
                ->end()
                ->arrayNode('fallback_languages')
                    ->prototype('array')
                        ->prototype('scalar')->end()
                    ->end()
                ->end()
                ->arrayNode('facets')
                    ->prototype('array')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('alias')->defaultValue(null)->end()
                            ->scalarNode('paramName')->defaultValue(null)->end()
                            ->scalarNode('field')->defaultValue(null)->end()
                            ->scalarNode('facetField')->defaultValue(null)->end()
                            ->scalarNode('filterField')->defaultValue(null)->end()
                            ->scalarNode('multiSelect')->defaultValue(true)->end()
                            ->scalarNode('hierarchical')->defaultValue(false)->end()
                            ->scalarNode('display')->defaultValue('2column')->end()
                            ->scalarNode('type')->defaultValue('enum')->end()
                            ->arrayNode('ranges')
                                ->prototype('array')
                                    ->children()
                                        ->scalarNode('from')->end()
                                        ->scalarNode('to')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('project_settings')
                    ->children()
                        ->arrayNode('countries')
                            ->requiresAtLeastOneElement()
                            ->prototype('scalar')
                                ->beforeNormalization()
                                    ->always()
                                    ->then(function ($v) { return strtoupper($v); })
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('currencies')
                            ->requiresAtLeastOneElement()
                            ->prototype('scalar')
                                ->beforeNormalization()
                                    ->always()
                                    ->then(function ($v) { return strtoupper($v); })
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('languages')
                            ->requiresAtLeastOneElement()
                            ->prototype('scalar')->end()
                        ->end()
                        ->scalarNode('name')->end()
                        ->arrayNode('messages')
                            ->beforeNormalization()
                                ->always()
                                ->then(function ($v) { return ['enabled' => $v]; })
                            ->end()
                            ->children()
                                ->booleanNode('enabled')->end()
                            ->end()
                        ->end()
                        ->arrayNode('shipping_rate_input_type')
                            ->children()
                                ->scalarNode('type')->isRequired()->end()
                                ->arrayNode('values')
                                    ->prototype('array')
                                        ->children()
                                            ->scalarNode('key')->end()
                                            ->arrayNode('label')
                                                ->prototype('scalar')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('channels')
                    ->prototype('array')
                        ->children()
                            ->arrayNode('roles')
                                ->prototype('scalar')->end()
                            ->end()
                            ->arrayNode('name')
                                ->prototype('scalar')->end()
                            ->end()
                            ->arrayNode('description')
                                ->prototype('scalar')->end()
                            ->end()
                            ->arrayNode('address')
                                ->children()
                                    ->scalarNode('country')->isRequired()->end()
                                    ->scalarNode('id')->end()
                                    ->scalarNode('key')->end()
                                    ->scalarNode('title')->end()
                                    ->scalarNode('salutation')->end()
                                    ->scalarNode('firstName')->end()
                                    ->scalarNode('lastName')->end()
                                    ->scalarNode('streetName')->end()
                                    ->scalarNode('streetNumber')->end()
                                    ->scalarNode('additionalStreetInfo')->end()
                                    ->scalarNode('postalCode')->end()
                                    ->scalarNode('city')->end()
                                    ->scalarNode('region')->end()
                                    ->scalarNode('state')->end()
                                    ->scalarNode('company')->end()
                                    ->scalarNode('department')->end()
                                    ->scalarNode('building')->end()
                                    ->scalarNode('apartment')->end()
                                    ->scalarNode('pOBox')->end()
                                    ->scalarNode('phone')->end()
                                    ->scalarNode('mobile')->end()
                                    ->scalarNode('email')->end()
                                    ->scalarNode('fax')->end()
                                    ->scalarNode('additionalAddressInfo')->end()
                                    ->scalarNode('externalId')->end()
                                ->end()
                            ->end()
//                            ->arrayNode('custom') // TODO maybe remove this at all
//                                ->children()
//                                    ->scalarNode('type')->end()
//                                    ->scalarNode('fields')->end() // TODO not correct
//                                ->end()
//                            ->end()
                            ->arrayNode('geoLocation')
                                ->children()
                                    ->scalarNode('type')->end()
                                    ->arrayNode('coordinates')
                                        ->prototype('scalar')
                                            ->beforeNormalization()
                                                ->ifString()
                                                ->then(function ($v) { return (float)$v; })
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
