<?php
/**
 */

namespace Commercetools\Symfony\CtpBundle\DependencyInjection;


use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder('commercetools');
        $rootNode = $this->getRootNode($treeBuilder, 'commercetools');

        $rootNode
            ->children()
                ->arrayNode('api')
                    ->addDefaultsIfNotSet()
                    ->fixXmlConfig('client')
                    ->children()
                        ->scalarNode('default_client')->defaultValue('default')->end()
                        ->arrayNode('clients')
                            ->useAttributeAsKey('name')
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('client_id')->isRequired()->end()
                                    ->scalarNode('client_secret')->isRequired()->end()
                                    ->scalarNode('project')->isRequired()->end()
                                    ->scalarNode('scope')->end()
                                    ->scalarNode('api_url')->end()
                                    ->scalarNode('oauth_url')->end()
                                    ->booleanNode('throwExceptions')->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('defaults')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('country')->defaultValue('DE')->end()
                        ->arrayNode('context')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('locale')->defaultValue('en')->end()
//                                ->scalarNode('currency')->defaultValue('EUR')->end()
                                ->booleanNode('graceful')->defaultValue(true)->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('cache')
                    ->children()
                        ->booleanNode('setup')->end()
                        ->booleanNode('states')->end()
                        ->booleanNode('customer')->end()
                        ->booleanNode('catalog')->end()
                        ->booleanNode('cart')->end()
                        ->booleanNode('shipping_method')->end()
                        ->booleanNode('order')->end()
                        ->booleanNode('payment')->end()
                        ->booleanNode('shopping_list')->end()
                        ->booleanNode('review')->end()
                    ->end()
                ->end()
                ->arrayNode('fallback_languages')
                    ->fixXmlConfig('language')
                    ->prototype('array')
                        ->prototype('scalar')->end()
                    ->end()
                ->end()
                ->arrayNode('facets')
                    ->prototype('array')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('alias')->defaultValue(null)->end()
                            ->scalarNode('paramName')->defaultValue(null)->end()
                            ->scalarNode('field')->defaultValue(null)->end()
                            ->scalarNode('facetField')->defaultValue(null)->end()
                            ->scalarNode('filterField')->defaultValue(null)->end()
                            ->scalarNode('multiSelect')->defaultValue(true)->end()
                            ->scalarNode('hierarchical')->defaultValue(false)->end()
                            ->scalarNode('display')->defaultValue('2column')->end()
                            ->scalarNode('type')->defaultValue('enum')->end()
                            ->arrayNode('ranges')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('from')->end()
                                        ->scalarNode('to')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('project_settings')
                    ->fixXmlConfig('country', 'countries')
                    ->fixXmlConfig('currency', 'currencies')
                    ->fixXmlConfig('language')
                    ->children()
                        ->arrayNode('countries')
                            ->requiresAtLeastOneElement()
                            ->prototype('scalar')
                                ->beforeNormalization()
                                    ->always()
                                    ->then(function ($v) { return strtoupper($v); })
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('currencies')
                            ->requiresAtLeastOneElement()
                            ->prototype('scalar')
                                ->beforeNormalization()
                                    ->always()
                                    ->then(function ($v) { return strtoupper($v); })
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('languages')
                            ->requiresAtLeastOneElement()
                            ->prototype('scalar')->end()
                        ->end()
                        ->scalarNode('name')->end()
                        ->arrayNode('messages')
                            ->beforeNormalization()
                                ->ifTrue(function ($v) { return !is_array($v); })
                                ->then(function ($v) { return ['enabled' => $v == true ?? false]; })
                            ->end()
                            ->children()
                                ->booleanNode('enabled')->end()
                            ->end()
                        ->end()
                        ->arrayNode('shipping_rate_input_type')
                            ->children()
                                ->scalarNode('type')->isRequired()->end()
                                ->arrayNode('values')
                                    ->prototype('array')
                                        ->children()
                                            ->scalarNode('key')->end()
                                            ->arrayNode('label')
                                                ->prototype('scalar')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }

    private function getRootNode(TreeBuilder $treeBuilder, $name)
    {
        // BC layer for symfony/config 4.1 and older
        if ( ! \method_exists($treeBuilder, 'getRootNode')) {
            return $treeBuilder->root($name);
        }
        return $treeBuilder->getRootNode();
    }
}
